# Generated by Django 3.0.7 on 2020-11-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0003_add_new_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedAccessDrip',
            fields=[
            ],
            options={
                'verbose_name': 'Drip',
                'verbose_name_plural': 'Drips',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('drip.drip',),
        ),
    ]
